### ISSUE TITLE
general clean up and code organization 

### ISSUE THREAD

**Issue by samfrons** [watson-developer-cloud/company-insights#10]

**Comment by nfriedly** [comment]
@samfrons I'm working on removing some of the unused code. Can you glance at the bower.json and package.json dependencies and tell me what you know off the top of your head that we're using or not using? I'll dig in a figure out the rest, but this will help me get a jumpstart on it.

[bower.json](https://github.com/watson-developer-cloud/company-insights/blob/master/bower.json) & [package.json](https://github.com/watson-developer-cloud/company-insights/blob/master/package.json)

[edit]: I went and started removing things, so far I've pulled out about half of bower.json and the app still seems to operate smoothly. So, instead of keeping an outdated copy in here, I'm just linking to the current revision.
